# Platform detection and configuration
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(PLATFORM_WINDOWS TRUE)
    set(PLATFORM_DESKTOP TRUE)
    set(PLATFORM_NAME "windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    if(IOS)
        set(PLATFORM_IOS TRUE)
        set(PLATFORM_MOBILE TRUE)
        set(PLATFORM_NAME "ios")
    else()
        set(PLATFORM_MACOS TRUE)
        set(PLATFORM_DESKTOP TRUE)
        set(PLATFORM_NAME "macos")
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PLATFORM_LINUX TRUE)
    set(PLATFORM_DESKTOP TRUE)
    set(PLATFORM_NAME "linux")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(PLATFORM_ANDROID TRUE)
    set(PLATFORM_MOBILE TRUE)
    set(PLATFORM_NAME "android")
elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
    set(PLATFORM_IOS TRUE)
    set(PLATFORM_MOBILE TRUE)
    set(PLATFORM_NAME "ios")
endif()

# Size optimization flags
if(MSVC)
    set(CMAKE_C_FLAGS_RELEASE "/Os /GL /MT")
    set(CMAKE_CXX_FLAGS_RELEASE "/Os /GL /MT")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/OPT:REF /OPT:ICF /LTCG")
else()
    set(CMAKE_C_FLAGS_RELEASE "-Os -ffunction-sections -fdata-sections")
    set(CMAKE_CXX_FLAGS_RELEASE "-Os -ffunction-sections -fdata-sections")
    if(NOT APPLE)
        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-Wl,--gc-sections -s")
    else()
        set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-Wl,-dead_strip")
    endif()
endif()
